config/routes.rb
Forecaster::Application.routes.draw do

  resources :companies do
    resources :stocks, only: [:index]
    resources :classifications
    resources :messages do 
      get 'import', on: :collection
    end
  end

  root to: 'companies#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :company

  def classification
    company.classifier.classify(title)
  end

  def as_json(options={})
    {
      :x => date.to_datetime.to_i * 1000,
      :title => classification.upcase[0],
      :text => title
    }
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_company
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  def index
    # get IDs of last 1000 messages (find_each doesn't support limit)
    ids = @company.messages.order(:id => :desc).limit(1000).pluck(:id) 
    @messages = @company.messages.where(:id => ids.min..ids.max)

    respond_to do |format|
      format.html # index.html.erb
      format.json # use own render because of faster loading by find_each method
    end
  end

  # GET /messages/1
  def show
  end

  # GET /messages/new
  def new
    @message = @company.messages.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  def create
    @message = @company.messages.new(message_params)

    if @message.save
      redirect_to company_message_url(@company, @message), notice: 'Message was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /messages/1
  def update
    if @message.update(message_params)
      redirect_to company_message_url(@company, @message), notice: 'Message was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /messages/1
  def destroy
    @message.destroy
    redirect_to company_messages_url(@company)
  end

  def import
    @company.import_messages
    redirect_to :back, notice: "Messages for #{@company.name} was successfully imported."
  rescue
    redirect_to :back, notice: "Import was not successful"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find_by(code: params[:company_id])
    end

    def set_message
      @message = @company.messages.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:company_id, :title, :link, :date, :content_html, :content_text)
    end
end

app/views/messages/_form.html.erb
<%= simple_form_for([@company, @message], :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :company %>
    <%= f.input :title %>
    <%= f.input :link %>
    <%= f.input :date %>
    <%= f.input :content_html %>
    <%= f.input :content_text %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, nil, :class => 'btn btn-primary', :disable_with => t('buttons.wait') %>
    <%= link_to t('buttons.cancel'), company_messages_path(@company), :class => 'btn' %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<% title "Editing Message" %>

<%= render 'form' %>

app/views/messages/index.html.erb
<% title "Listing messages" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Message.human_attribute_name(:company) %></th>
      <th><%= Message.human_attribute_name(:title) %></th>
      <th><%= Message.human_attribute_name(:link) %></th>
      <th><%= Message.human_attribute_name(:date) %></th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <%= content_tag_for(:tr, @messages) do |message| %>
      <td><%= link_to message.company.name, message.company %></td>
      <td><%= message.title %></td>
      <td><%= link_to "See", message.link %></td>
      <td><%= localize message.date, format: :long %></td>
      <td>
        <%= link_to t('buttons.show'), company_message_path(@company, message), class: 'btn btn-mini btn-primary' %>
        <%= link_to t('buttons.edit'), edit_company_message_path(@company, message), class: 'btn btn-mini' %>
        <%= link_to t('buttons.delete'), company_message_path(@company, message), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to t('buttons.new'), new_company_message_path(@company), class: 'btn btn-primary' %>
<%= link_to t('buttons.import'), import_company_messages_path(@company), class: 'btn' %>

app/views/messages/index.json.erb
[
<% @messages.find_each(:batch_size => 100) do |message| %>
  <%= raw message.to_json %><% unless @messages.last == message %>,<% end %>
<% end %>
]

app/views/messages/new.html.erb
<% title "New Message" %>

<%= render 'form' %>

app/views/messages/show.html.erb
<% title "Message details" %>

<table class="table table-attributes">
  <tbody>
    <tr>
      <th><%= Message.human_attribute_name(:company) %></th>
      <td><%= link_to @message.company.name, @message.company %></td>
    </tr>
    
    <tr>
      <th><%= Message.human_attribute_name(:title) %></th>
      <td><%= @message.title %></td>
    </tr>
    
    <tr>
      <th><%= Message.human_attribute_name(:link) %></th>
      <td><%= link_to @message.link %></td>
    </tr>
    
    <tr>
      <th><%= Message.human_attribute_name(:date) %></th>
      <td><%= localize @message.date %></td>
    </tr>
    
    <tr>
      <th><%= Message.human_attribute_name(:content_html) %></th>
      <td><%= raw @message.content_html %></td>
    </tr>
    
  </tbody>
</table>


<div class="form-actions">
<%= link_to t('buttons.edit'), edit_company_message_path(@company, @message), :class => 'btn btn-primary' %>
<%= link_to t('buttons.delete'), company_message_path(@company, @message), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
<%= link_to t('buttons.back'), company_messages_path(@company), :class => 'btn' %>
</div>