config/routes.rb
Forecaster::Application.routes.draw do

  resources :companies do
    resources :stocks, only: [:index]
    resources :classifications
    resources :messages do 
      get 'import', on: :collection
    end
  end

  root to: 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  include ActionView::Helpers

  has_many :messages,        dependent: :destroy
  has_many :stocks,          dependent: :destroy
  has_many :classifications, dependent: :destroy

  validates :name, :code, :messages_url, :stocks_url, presence: true
  validates :code, uniqueness: true

  after_create :import_stocks
  after_create :import_messages

  def import_stocks
    require 'open-uri'
    require 'csv'

    rows = CSV.parse(open(stocks_url).read).reverse
    header = rows.pop.map { |s| s.parameterize.underscore.to_sym } # [:date, :open, :high, :low, :close]

    transaction do
      rows.each do |i|
        row = Hash[[header, i].transpose]
        stocks.create! do |stock|
          stock.date  = Date.strptime(row[:date]) #, '%m-%d-%Y')
          stock.open  = row[:open]
          stock.high  = row[:high]
          stock.low   = row[:low]
          stock.close = row[:close]
        end
      end
    end
  end

  def import_messages
    require 'open-uri'
    require 'rss'
    require 'htmlentities'

    rss = RSS::Parser.parse(open(messages_url).read, false)

    transaction do
      rss.items.reverse.each do |item|
        message = messages.where(link: item.link).first_or_initialize
        if message.new_record?
          message.title = HTMLEntities.new.decode(item.title).squish.strip
          message.date  = item.date
          message.content_html = item.description
          message.content_text = HTMLEntities.new.decode(sanitize(item.description)).squish.strip
          message.save! unless message.content_html.blank? || message.content_text.blank?
        end
      end
    end
  end

  def classifier
    unless defined?(@classifier)
      require 'classifier'
      
      @classifier = Classifier::Bayes.new('positive', 'negative')
      classifications.positive.pluck(:text).each { |s| @classifier.train(:positive, s) }
      classifications.negative.pluck(:text).each { |s| @classifier.train(:negative, s) }
    end

    @classifier
  end

  def to_param
    code
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  def index
    @companies = Company.all
  end

  # GET /companies/1
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /companies/1
  def update
    if @company.update(company_params)
      redirect_to @company, notice: 'Company was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /companies/1
  def destroy
    @company.destroy
    redirect_to companies_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find_by(code: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :description, :code, :messages_url, :stocks_url)
    end
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company, :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :code %>
    <%= f.input :messages_url %>
    <%= f.input :stocks_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, nil, :class => 'btn btn-primary' %>
    <%= link_to t('buttons.cancel'), companies_path, :class => 'btn' %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<% title "Editing Company" %>

<%= render 'form' %>

app/views/companies/index.html.erb
<% title "Listing companies" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Company.human_attribute_name(:name) %></th>
      <th><%= Company.human_attribute_name(:description) %></th>
      <th><%= Company.human_attribute_name(:code) %></th>
      <th><%= Company.human_attribute_name(:messages_url) %></th>
      <th><%= Company.human_attribute_name(:stocks_url) %></th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <%= content_tag_for(:tr, @companies) do |company| %>
      <td><%= company.name %></td>
      <td><%= company.description %></td>
      <td><%= company.code %></td>
      <td><%= link_to "See", company.messages_url %></td>
      <td><%= link_to "See", company.stocks_url %></td>
      <td>
        <%= link_to t('buttons.show'), company, class: 'btn btn-mini btn-primary' %>
        <%= link_to t('buttons.edit'), edit_company_path(company), class: 'btn btn-mini' %>
        <%= link_to t('buttons.delete'), company, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to t('buttons.new'), new_company_path, class: 'btn btn-primary' %>

app/views/companies/new.html.erb
<% title "New Company" %>

<%= render 'form' %>

app/views/companies/show.html.erb
<% title "Company details" %>

<table class="table table-attributes">
  <tbody>
    <tr>
      <th><%= Company.human_attribute_name(:name) %></th>
      <td><%= @company.name %></td>
    </tr>
    
    <tr>
      <th><%= Company.human_attribute_name(:description) %></th>
      <td><%= @company.description %></td>
    </tr>
    
    <tr>
      <th><%= Company.human_attribute_name(:code) %></th>
      <td><%= @company.code %></td>
    </tr>
    
    <tr>
      <th><%= Company.human_attribute_name(:messages_url) %></th>
      <td><%= link_to @company.messages_url %></td>
    </tr>
    
    <tr>
      <th><%= Company.human_attribute_name(:stocks_url) %></th>
      <td><%= link_to @company.stocks_url %></td>
    </tr>
    
  </tbody>
</table>


<div class="form-actions">
<%= link_to t('buttons.edit'), edit_company_path(@company), :class => 'btn btn-primary' %>
<%= link_to t('buttons.delete'), company_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
<%= link_to t('buttons.back'), companies_path, :class => 'btn' %>
</div>