config/routes.rb
Forecaster::Application.routes.draw do

  resources :companies do
    resources :stocks, only: [:index]
    resources :classifications
    resources :messages do 
      get 'import', on: :collection
    end
  end

  root to: 'companies#index'

end

app/models/classification.rb
class Classification < ActiveRecord::Base
  belongs_to :company

  scope :positive, lambda { where(category: 'positive') }
  scope :negative, lambda { where(category: 'negative') }
end

app/controllers/classifications_controller.rb
class ClassificationsController < ApplicationController
  before_action :set_company
  before_action :set_classification, only: [:show, :edit, :update, :destroy]

  # GET /classifications
  def index
    @classifications = @company.classifications.all
  end

  # GET /classifications/1
  def show
  end

  # GET /classifications/new
  def new
    @classification = @company.classifications.new
  end

  # GET /classifications/1/edit
  def edit
  end

  # POST /classifications
  def create
    @classification = @company.classifications.new(classification_params)

    if @classification.save
      redirect_to company_classification_url(@company, @classification), notice: 'Classification was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /classifications/1
  def update
    if @classification.update(classification_params)
      redirect_to company_classification_url(@company, @classification), notice: 'Classification was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /classifications/1
  def destroy
    @classification.destroy
    redirect_to company_classifications_url(@company)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find_by(code: params[:company_id])
    end

    def set_classification
      @classification = @company.classifications.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classification_params
      params.require(:classification).permit(:company_id, :text, :category)
    end
end

app/views/classifications/_form.html.erb
<%= simple_form_for([@company, @classification], :html => { :class => 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :company %>
    <%= f.input :text %>
    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, nil, :class => 'btn btn-primary' %>
    <%= link_to t('buttons.cancel'), company_classifications_path(@company), :class => 'btn' %>
  </div>
<% end %>

app/views/classifications/edit.html.erb
<% title "Editing Classification" %>

<%= render 'form' %>

app/views/classifications/index.html.erb
<% title "Listing classifications" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Classification.human_attribute_name(:company) %></th>
      <th><%= Classification.human_attribute_name(:text) %></th>
      <th><%= Classification.human_attribute_name(:category) %></th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <%= content_tag_for(:tr, @classifications) do |classification| %>
      <td><%= link_to classification.company.name, classification.company %></td>
      <td><%= classification.text %></td>
      <td><%= classification.category %></td>
      <td>
        <%= link_to t('buttons.show'), company_classification_path(@company, classification), class: 'btn btn-mini btn-primary' %>
        <%= link_to t('buttons.edit'), edit_company_classification_path(@company, classification), class: 'btn btn-mini' %>
        <%= link_to t('buttons.delete'), company_classification_path(@company, classification), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini btn-danger' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to t('buttons.new'), new_company_classification_path(@company), class: 'btn btn-primary' %>

app/views/classifications/new.html.erb
<% title "New Classification" %>

<%= render 'form' %>

app/views/classifications/show.html.erb
<% title "Classification details" %>

<table class="table table-attributes">
  <tbody>
    <tr>
      <th><%= Classification.human_attribute_name(:company) %></th>
      <td><%= link_to @classification.company.name, @classification.company %></td>
    </tr>
    
    <tr>
      <th><%= Classification.human_attribute_name(:text) %></th>
      <td><%= @classification.text %></td>
    </tr>
    
    <tr>
      <th><%= Classification.human_attribute_name(:category) %></th>
      <td><%= @classification.category %></td>
    </tr>
    
  </tbody>
</table>


<div class="form-actions">
<%= link_to t('buttons.edit'), edit_company_classification_path(@company, @classification), :class => 'btn btn-primary' %>
<%= link_to t('buttons.delete'), company_classification_path(@company, @classification), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
<%= link_to t('buttons.back'), company_classifications_path(@company), :class => 'btn' %>
</div>