config/routes.rb
Forecaster::Application.routes.draw do

  resources :companies do
    resources :stocks, only: [:index]
    resources :classifications
    resources :messages do 
      get 'import', on: :collection
    end
  end

  root to: 'companies#index'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper

  def title(page_title)
    content_for(:title) { h(page_title.to_s) }
  end

  def description(page_description)
    content_for(:description) { h(page_description.to_s) }
  end

  def keywords(page_keywords)
    content_for(:keywords) { h(page_keywords.to_s) }
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end

  def meta(*args)
    content_for(:head) { meta_tag(*args) }
  end
  
  
  # Renders a title tag for use in the HEAD section of an html document.
  def title_tag(title)
    content_tag :title, strip_tags(title).strip
  end

  # Renders a description meta tag for use in the HEAD section of an html document.
  def description_meta_tag(description)
    meta_tag :description, strip_tags(description).strip
  end

  # Renders a keywords meta tag for use in the HEAD section of an html document.
  def keywords_meta_tag(keywords)
    meta_tag :keywords, strip_tags(keywords).strip
  end

  # Renders a meta tag for use in the HEAD section of an html document.
  def meta_tag(name, value, http_equiv = false)
    return nil if value.blank?
    http_equiv = true if %w{expires pragma content-type content-script-type content-style-type default-style content-language refresh window-target cache-control vary}.include? name
    if http_equiv
      tag :meta, :"http-equiv" => name, :content => value
    else 
      tag :meta, :name => name, :content => value
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title><%= content_for?(:title) ? yield(:title) : "Forecaster" %></title>
  <%= description_meta_tag yield(:description) %>
  <%= keywords_meta_tag yield(:keywords) %>
  <%= csrf_meta_tags %>
  <%= meta_tag('robots', "noindex, nofollow, noarchive") unless Rails.env.production? %>
  <%= meta_tag('viewport', "width=device-width, initial-scale=1.0") %>

  <%= favicon_link_tag "/favicon.ico" %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script><![endif]-->
  <%= yield(:head) %>
</head>
<body>
  <header>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Forecaster", root_path, class: "brand" %>
          <div class="nav-collapse">
            <ul class="nav">
              <%= content_tag :li, class: (controller?('companies') ? "active" : nil) do %>
                <%= link_to "Companies", companies_path %>
              <% end %>
              <%= content_tag :li, class: (controller?('messages') ? "active" : nil) do %>
                <%= link_to "Messages", company_messages_path(@company) %>
              <% end if @company %>
              <%= content_tag :li, class: (controller?('stocks') ? "active" : nil) do %>
                <%= link_to "Stocks", company_stocks_path(@company) %>
              <% end if @company %>
              <%= content_tag :li, class: (controller?('classifications') ? "active" : nil) do %>
                <%= link_to "Classifications", company_classifications_path(@company) %>
              <% end if @company %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div id="flashes">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) && !msg.blank? %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">×</a>
          <%= content_tag :div, raw(msg), :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
    </div>

    <div class="row">
      <div id="content" class="span12">
        <%= content_tag :h1, yield(:title) %>
        <%= yield %>
      </div>
    </div>


    <footer>
      <hr />
      <p class="pull-left">&copy; 2013 <%= " - #{Date.today.year}" if Date.today.year > 2013 %></p>
      <p class="pull-right">
        <%#= link_to "Admin" %>
      </p>
    </footer>

  </div>
</body>
</html>